### ISSUE TITLE
Check for valid orientation vectors

### ISSUE THREAD

**Issue by gwolf-011235** [u413-284-si/miniRT#23]
While checking input all given _3d normalized orientation vectors_ should be checked, if they are indeed unit vectors.

- If not: vector could be normalized anyway and just print out a warning
- Special case (0,0,0): can't be normalized - in this case abort?

**Comment by u413-284-si** [comment]
That was part of the bug fixes I implemented yesterday. The parsed orientation vectors at times were not normalised. After I normalised them the code worked (partly) again. So yes, we can accept them, but should normalise them for usage. It's part of my code already. Will be merged later on.

Triple 0 means there is no orientation, therefore cam is looking nowhere. This should not be accepted.

**Comment by gwolf-011235** [comment]
Where did you implement it? In the check/parse part or later while tracing? If later I would move into check/parse. Then we can be assured that all orientation vectors are normalized, when we begin working.

Is Triple 0 a special case which could/should be added to ft_vec3_norm()? 
Right now it makes a zero division, if length (ft_vec3_abs()) is zero. Since it's float nobody gets hurt, but we could get some problems with angry mathematicians in a bar.

**Comment by u413-284-si** [comment]
I implemented it in the parser, right after parsing the vector. So should be fine. And I think I deactivated the check, will look at that again.

Yes, to be correct we should also avoid dividing by 0 with the calculations of the absolute of a vector. Those mathematicians shall not be roused.
